using System.ComponentModel.DataAnnotations;

namespace PruebasGraficas.Classes.Models
{
    public abstract class BaseEntity
    {
        public int Id { get; set; }

        [Timestamp]
        public byte[] RowVersion { get; set; } = [];

        [MaxLength(200)]
        public string ModifiedBy { get; set; } = "System";

        public DateTime ModifiedDate { get; set; } = DateTime.UtcNow;

        [MaxLength(200)]
        public string CreatedBy { get; set; } = "System";

        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

        public bool IsActive { get; set; } = true;

        protected BaseEntity()
        {
            // Keep timestamps consistent and server-generated by default.
            CreatedDate = DateTime.UtcNow;
            ModifiedDate = DateTime.UtcNow;
        }
    }

    public abstract class BaseRequest
    {
        [Key]
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public required string ModifiedBy { get; set; }
        public byte[]? RowVersion { get; set; }
    }


    public abstract class BaseResponse
    {
        [Key]
        public int Id { get; set; }
        public string? ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public byte[]? RowVersion { get; set; }
    }
}
